In [1]:
import pandas as pd
import numpy as np
import re

from sklearn.model_selection import train_test_split

In [2]:
TRAIN_PATH = "../data/HeadHunter_train_orig.csv"
TEST_PATH = "../data/HeadHunter_test.csv"

NEW_TRAIN_PATH = "../data/HeadHunter_train.csv"
NEW_VAL_PATH = "../data/HeadHunter_val.csv"

In [31]:
true_s = "Когда я закончила универ и искала работу, в «******» открылась вакансия дизайнера."
true_s_1 = "****** открылась вакансия дизайнера."
false_s = "**************"

In [98]:
pattern = r'([^\*]|^)\*{6}([^\*])'

In [99]:
re.sub(pattern, r'\1компания\2', true_s)

'Когда я закончила универ и искала работу, в «компания» открылась вакансия дизайнера.'

In [103]:
re.sub(pattern, r'\1компания\2', true_s_1)

'компания открылась вакансия дизайнера.'

In [102]:
re.sub(pattern, r'\1компания\2', false_s)

'**************'

In [3]:
train = pd.read_csv(TRAIN_PATH)
test = pd.read_csv(TEST_PATH)

In [5]:
train.head()

review_id             city              position  \
0          0           Ижевск             Кладовщик   
1          1           Москва  Руководитель проекта   
2          2     Екатеринбург           Консультант   
3          5  Санкт-Петербург              Оператор   
4          7           Москва         Инженер КИПиА   

                                            positive  \
0  Недавно устроился в ****** на должность кладов...   
1  Расположение офиса, своего рода стабильность (...   
2  В нашем банке все по закону в плане зарплаты и...   
3  Я в ****** около года работаю оператором. Норм...   
4                     В принципе норм.Работать можно   

                                            negative  salary_rating  \
0                                       Повысить з/п              5   
1  Упростить процессы - все процессы ради процесс...              4   
2                                             Ничего              5   
3                                               Нет.              5   
4                      Всегда есть к чему стремиться              4   

   team_rating  managment_rating  career_rating  workplace_rating  \
0            4                 3              3                 4   
1            4                 4              1                 1   
2            5                 5              5                 5   
3            5                 5              5                 5   
4            5                 4              2                 5   

   rest_recovery_rating target  
0                     4      0  
1                     1      8  
2                     5      0  
3                     5      0  
4                     2      8

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50876 entries, 0 to 50875
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   review_id             50876 non-null  int64 
 1   city                  47525 non-null  object
 2   position              46218 non-null  object
 3   positive              50837 non-null  object
 4   negative              50739 non-null  object
 5   salary_rating         50876 non-null  int64 
 6   team_rating           50876 non-null  int64 
 7   managment_rating      50876 non-null  int64 
 8   career_rating         50876 non-null  int64 
 9   workplace_rating      50876 non-null  int64 
 10  rest_recovery_rating  50876 non-null  int64 
 11  target                50876 non-null  object
dtypes: int64(7), object(5)
memory usage: 4.7+ MB


In [8]:
train.describe()

review_id  salary_rating   team_rating  managment_rating  \
count   50876.000000   50876.000000  50876.000000      50876.000000   
mean    96570.377369       3.444827      4.144548          3.520226   
std     55769.347840       1.478828      1.275873          1.592045   
min         0.000000       1.000000      1.000000          1.000000   
25%     48183.750000       2.000000      4.000000          2.000000   
50%     96594.500000       4.000000      5.000000          4.000000   
75%    145021.250000       5.000000      5.000000          5.000000   
max    192828.000000       5.000000      5.000000          5.000000   

       career_rating  workplace_rating  rest_recovery_rating  
count   50876.000000      50876.000000          50876.000000  
mean        3.386115          3.728025              3.409781  
std         1.558145          1.457538              1.612926  
min         0.000000          1.000000              1.000000  
25%         2.000000          3.000000              2.000000  
50%         4.000000          4.000000              4.000000  
75%         5.000000          5.000000              5.000000  
max         5.000000          5.000000              5.000000

In [17]:
test.head()

review_id    city                  position  \
0          3  Москва        Старший специалист   
1          4  Москва     Менеджер по персоналу   
2         13   Тверь          Тренинг-менеджер   
3         14     Уфа  Специалист отдела кадров   
4         17  Москва           Бизнес-аналитик   

                                            positive  \
0   Свобода в выборе рабочего графика, условия труда   
1  Компания делает ставки на молодых и перспективных   
2                     Есть возможность для  развития   
3  Хороший коллектив, размереная работа, нет пере...   
4             Гибкость в рабочем графике, коллектив.   

                                            negative  salary_rating  \
0          ****** всегда стремится к улучшению всего              5   
1  Слабая оснащённость рабочих мест, отсутствие Д...              4   
2                           Увеличить уровень дохода              2   
3  Обучение сотрудников,  ротацию кадров, увеличе...              2   
4                Уровень представленности HR-бренда.              5   

   team_rating  managment_rating  career_rating  workplace_rating  \
0            5                 5              5                 5   
1            5                 4              5                 4   
2            5                 5              5                 5   
3            5                 5              2                 4   
4            5                 5              5                 5   

   rest_recovery_rating  
0                     5  
1                     4  
2                     5  
3                     4  
4                     5

In [18]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50651 entries, 0 to 50650
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   review_id             50651 non-null  int64 
 1   city                  47558 non-null  object
 2   position              48424 non-null  object
 3   positive              50650 non-null  object
 4   negative              50648 non-null  object
 5   salary_rating         50651 non-null  int64 
 6   team_rating           50651 non-null  int64 
 7   managment_rating      50651 non-null  int64 
 8   career_rating         50651 non-null  int64 
 9   workplace_rating      50651 non-null  int64 
 10  rest_recovery_rating  50651 non-null  int64 
dtypes: int64(7), object(4)
memory usage: 4.3+ MB


In [19]:
test.describe()

review_id  salary_rating   team_rating  managment_rating  \
count   50651.000000   50651.000000  50651.000000      50651.000000   
mean    96025.555527       3.316736      4.126098          3.475687   
std     55548.868165       1.452530      1.281285          1.586697   
min         3.000000       1.000000      1.000000          1.000000   
25%     47736.000000       2.000000      4.000000          2.000000   
50%     95875.000000       3.000000      5.000000          4.000000   
75%    143999.000000       5.000000      5.000000          5.000000   
max    192833.000000       5.000000      5.000000          5.000000   

       career_rating  workplace_rating  rest_recovery_rating  
count   50651.000000      50651.000000          50651.000000  
mean        3.314584          3.700855              3.302008  
std         1.550043          1.460323              1.610658  
min         0.000000          1.000000              1.000000  
25%         2.000000          3.000000              2.000000  
50%         4.000000          4.000000              4.000000  
75%         5.000000          5.000000              5.000000  
max         5.000000          5.000000              5.000000

In [20]:
train_positive_texts = list(train["positive"])
train_negative_texts = list(train["negative"])

test_positive_texts = list(test["positive"])
test_negative_texts = list(test["negative"])

In [24]:
"" in test_positive_texts, " " in test_positive_texts, "" in test_negative_texts, " " in test_negative_texts

(False, False, False, False)

In [28]:
test_pos_lens = list(map(lambda x: len(str(x)), test_positive_texts))

In [33]:
min_len, max_len = min(test_pos_lens), max(test_pos_lens)

In [35]:
for _text in test_positive_texts:
    if type(_text) is not str:
        print("Not str:", _text, end="\n\n")
    elif len(_text) == min_len:
        print("Min len:", _text, end="\n\n")
    elif len(_text) == max_len:
        print("Max len:", _text, end="\n\n")

Max len: The standard Lorem Ipsum passage, used since the 1500s "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum." Section 1.10.32 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem

In [46]:
for _text in test_positive_texts:
    if type(_text) is not str:
        print("Not str:", _text, end="\n\n")
    elif len(_text) in _text:
        print("Min len:", _text, end="\n\n")

Min len: *†********†****************

Min len: ************************

Min len: Мой прямой руководитель, все остальные - ********

Min len: ***************************

Min len: ********************************

Min len: ********************

Min len: ***************************************************************

Min len: *********************

Min len: —+++++++++**********

Min len: Ни чего ********************************************+++++++**+********

Min len: *************************

Min len: ********************

Not str: nan

Min len: *************************

Min len: ************************



In [8]:
help('modules')


Please wait a moment while I gather a list of all available modules...



/usr/local/lib/python3.8/dist-packages/IPython/kernel/__init__.py:12: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  warn("The `IPython.kernel` package has been deprecated since IPython 4.0."
/usr/lib/python3.8/pkgutil.py:107: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  yield from walk_packages(path, info.name+'.', onerror)
/usr/lib/python3/dist-packages/UpdateManager/backend/__init__.py:11: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GLib, Gtk, Snapd


AptUrl              array               ipaddress           reportlab
CommandNotFound     ast                 ipykernel           reprlib
DistUpgrade         async_generator     ipykernel_launcher  requests
HweSupportStatus    asynchat            ipython_genutils    requests_unixsocket
IPython             asyncio             ipywidgets          resource
LanguageSelector    asyncore            itertools           rlcompleter
NvidiaDetector      atexit              janitor             rmagic
PIL                 attr                jedi                runpy
Quirks              audioop             jinja2              scanext
UbuntuDrivers       autoreload          joblib              sched
UpdateManager       backcall            json                scipy
__future__          base64              jsonschema          secrets
_abc                bdb                 jupyter             secretstorage
_ast                binascii            jupyter_client      select
_asyncio            binhex    

In [4]:
! pip install scikit-multilearn

In [5]:
from skmultilearn.model_selection import iterative_train_test_split

ModuleNotFoundError: No module named 'skmultilearn'

In [ ]:
y = train['target']

In [51]:
y

0          0
1          8
2          0
3          0
4          8
        ... 
50871    3,8
50872      8
50873      8
50874      1
50875      0
Name: target, Length: 50876, dtype: object

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [26]:
from typing import List

In [21]:
a = np.zeros(9)

In [23]:
a[[1, 7]] = 1

In [24]:
a

array([0., 1., 0., 0., 0., 0., 0., 1., 0.])

In [18]:
a = np.zeros((1, 9))[:, [1, 7]] = 1

In [16]:
a[:, [1, 7]] = 1

In [19]:
a

1

In [27]:
def to_one_hot(row: List[int]) -> numpy.ndarray:
    res = np.zeros(9)
    res[row] = 1
    return res

In [28]:
type(a)

numpy.ndarray

In [29]:
to_one_hot([1])

array([0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
to_one_hot([0, 4, 8])

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])